'use client';
import {useEffect,useState} from 'react';

type Publication={id:string;status:string;postId?:string;url?:string;error?:string};
type Creator={nickname:string;privacyOptions:string[];commentDisabled:boolean;duetDisabled:boolean;stitchDisabled:boolean;maxDuration:number};
type Page={pageId:string;name:string;igId:string};
const csrf=()=>decodeURIComponent(document.cookie.split('; ').find(c=>c.startsWith('pc_csrf='))?.split('=')[1]||'');
async function api<T>(path:string,body?:unknown):Promise<T>{const r=await fetch('/api/v1/social/'+path,{method:body?'POST':'GET',headers:body?{'content-type':'application/json','x-csrf-token':csrf(),'idempotency-key':crypto.randomUUID()}:undefined,body:body?JSON.stringify(body):undefined});const data=await r.json();if(!r.ok)throw new Error(data.message||data.code||'Provider request failed');return data;}

export default function SocialPublishing({assetId,title}:{assetId:string;title:string}){
 const [tab,setTab]=useState<'tiktok'|'instagram'|'x'>('tiktok'),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [directEnabled,setDirectEnabled]=useState(false);
 const [creator,setCreator]=useState<Creator|null>(null),[privacy,setPrivacy]=useState(''),[ttCaption,setTtCaption]=useState(title),[comment,setComment]=useState(true),[duet,setDuet]=useState(false),[stitch,setStitch]=useState(false),[commercial,setCommercial]=useState<'none'|'own'|'paid'>('none'),[ai,setAi]=useState(false),[ttConsent,setTtConsent]=useState(false),[ttPost,setTtPost]=useState<Publication|null>(null);
 const [pages,setPages]=useState<Page[]>([]),[pageId,setPageId]=useState(''),[igCaption,setIgCaption]=useState(title),[shareFeed,setShareFeed]=useState(true),[igConsent,setIgConsent]=useState(false),[igPost,setIgPost]=useState<Publication|null>(null);
 const [xText,setXText]=useState(title.slice(0,280)),[xConsent,setXConsent]=useState(false),[xPost,setXPost]=useState<Publication|null>(null);
 useEffect(()=>{for(const [key,set] of [['tiktok',setTtPost],['instagram',setIgPost],['x',setXPost]] as const){const id=sessionStorage.getItem('pc_publish_'+key+'_'+assetId);if(id)set({id,status:'processing'});}},[assetId]);
 useEffect(()=>{api<{enabled:boolean}>('tiktok/availability').then(r=>setDirectEnabled(r.enabled)).catch(()=>{});},[]);
 async function action(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn();}catch(e){setError(e instanceof Error?e.message:'Request failed');}finally{setBusy(false);}}
 function remember(provider:string,p:Publication,set:(p:Publication)=>void){set(p);sessionStorage.setItem('pc_publish_'+provider+'_'+assetId,p.id);}
 return <section className="social-publishing" aria-label="Publish to social platforms"><div className="social-header"><div><span className="studio-kicker">DISTRIBUTION / REVIEW</span><h3>Take your clip live.</h3><p>Connect your own account, review the post, and publish when you are ready.</p></div><div className="social-tabs" role="tablist" aria-label="Choose platform">{(['tiktok','instagram','x'] as const).map(p=><button type="button" role="tab" aria-selected={tab===p} className={tab===p?'selected':''} key={p} onClick={()=>{setTab(p);setError('');}}>{p==='x'?'X':p==='tiktok'?'TikTok':'Instagram'}</button>)}</div></div>
 {error&&<p className="inline-error" role="alert">{error}</p>}
 {tab==='tiktok'&&<div className="social-fields" role="tabpanel"><p>Direct post from PUMPCLIP. Your TikTok account’s current privacy choices and limits are loaded before publishing.</p>{!directEnabled?<p className="social-account">Direct posting is awaiting TikTok permission, audit and a live account test. You can use the TikTok draft flow above.</p>:<><a href="/api/v1/social/tiktok?mode=publish">Connect TikTok for direct posting ↗</a><button className="download-button" disabled={busy} onClick={()=>action(async()=>{const info=await api<Creator>('tiktok/creator');setCreator(info);setPrivacy(info.privacyOptions[0]||'');setComment(!info.commentDisabled);setDuet(!info.duetDisabled);setStitch(!info.stitchDisabled);})}>Load account settings ↻</button></>}
 {creator&&<><div className="social-account">Posting as <strong>{creator.nickname}</strong> · Max video {creator.maxDuration}s</div><label>Privacy<select value={privacy} onChange={e=>setPrivacy(e.target.value)}>{creator.privacyOptions.map(v=><option key={v} value={v}>{v.replaceAll('_',' ').toLowerCase()}</option>)}</select></label><label>Caption<textarea maxLength={2200} rows={3} value={ttCaption} onChange={e=>setTtCaption(e.target.value)}/></label><div className="social-checks"><label><input type="checkbox" checked={comment} disabled={creator.commentDisabled} onChange={e=>setComment(e.target.checked)}/> Allow comments</label><label><input type="checkbox" checked={duet} disabled={creator.duetDisabled} onChange={e=>setDuet(e.target.checked)}/> Allow Duet</label><label><input type="checkbox" checked={stitch} disabled={creator.stitchDisabled} onChange={e=>setStitch(e.target.checked)}/> Allow Stitch</label></div><label>Commercial disclosure<select value={commercial} onChange={e=>setCommercial(e.target.value as typeof commercial)}><option value="none">None</option><option value="own">Promoting my own brand</option><option value="paid">Paid partnership</option></select></label><label className="social-check"><input type="checkbox" checked={ai} onChange={e=>setAi(e.target.checked)}/> This clip contains AI generated content</label><label className="social-check"><input type="checkbox" checked={ttConsent} onChange={e=>setTtConsent(e.target.checked)}/> I reviewed this clip, caption, disclosures and privacy and agree to post to TikTok.</label><button className="render-button" disabled={busy||!ttConsent||!privacy||!!ttPost} onClick={()=>action(async()=>remember('tiktok',await api<Publication>('tiktok/publish',{assetId,privacyLevel:privacy,caption:ttCaption,allowComment:comment,allowDuet:duet,allowStitch:stitch,commercial,aiGenerated:ai,consent:true}),setTtPost))}>Publish to TikTok ↗</button></>}
 {ttPost&&<div className="social-status" role="status">TikTok: {ttPost.status} {ttPost.postId&&'· Post '+ttPost.postId}<button disabled={busy} onClick={()=>action(async()=>setTtPost(await api<Publication>('tiktok/publish/'+ttPost.id)))}>Check status ↻</button></div>}</div>}
 {tab==='instagram'&&<div className="social-fields" role="tabpanel"><p>Reels require a linked professional Instagram account and a Facebook Page with content permission. Video import needs configured cloud media storage.</p><a href="/api/v1/social/instagram">Connect Instagram ↗</a><button className="download-button" disabled={busy} onClick={()=>action(async()=>{const result=await api<Page[]>('instagram/accounts');setPages(result);setPageId(result[0]?.pageId||'');})}>Load linked accounts ↻</button>{pages.length>0&&<><label>Instagram account<select value={pageId} onChange={e=>setPageId(e.target.value)}>{pages.map(p=><option key={p.pageId} value={p.pageId}>{p.name} · {p.igId}</option>)}</select></label><label>Reel caption<textarea maxLength={2200} rows={3} value={igCaption} onChange={e=>setIgCaption(e.target.value)}/></label><label className="social-check"><input type="checkbox" checked={shareFeed} onChange={e=>setShareFeed(e.target.checked)}/> Also share to feed</label><label className="social-check"><input type="checkbox" checked={igConsent} onChange={e=>setIgConsent(e.target.checked)}/> I reviewed the clip and caption and agree to publish to this Instagram account.</label><button className="render-button" disabled={busy||!igConsent||!!igPost} onClick={()=>action(async()=>remember('instagram',await api<Publication>('instagram/reels',{assetId,pageId,caption:igCaption,shareToFeed:shareFeed,consent:true}),setIgPost))}>Prepare Reel ↗</button></>}{igPost&&<div className="social-status" role="status">Instagram: {igPost.status}{igPost.postId&&' · Post '+igPost.postId}<div><button disabled={busy} onClick={()=>action(async()=>setIgPost(await api<Publication>('instagram/reels/'+igPost.id)))}>Check processing ↻</button>{igPost.status==='ready'&&<button disabled={busy||!igConsent} onClick={()=>action(async()=>setIgPost(await api<Publication>('instagram/reels/'+igPost.id,{consent:true})))}>Publish Reel ↗</button>}</div></div>}</div>}
 {tab==='x'&&<div className="social-fields" role="tabpanel"><p>Upload the video first, then publish your post after X finishes processing it.</p><a href="/api/v1/social/x">Connect X ↗</a><label>Post text <small>{xText.length}/280</small><textarea maxLength={280} rows={3} value={xText} onChange={e=>setXText(e.target.value)}/></label><label className="social-check"><input type="checkbox" checked={xConsent} onChange={e=>setXConsent(e.target.checked)}/> I reviewed the clip and text and agree to post to X.</label><button className="render-button" disabled={busy||!xConsent||!xText.trim()||!!xPost} onClick={()=>action(async()=>remember('x',await api<Publication>('x/videos',{assetId,text:xText,consent:true}),setXPost))}>Upload video to X ↗</button>{xPost&&<div className="social-status" role="status">X: {xPost.status}<div><button disabled={busy} onClick={()=>action(async()=>setXPost(await api<Publication>('x/videos/'+xPost.id)))}>Check processing ↻</button>{xPost.status==='ready'&&<button disabled={busy||!xConsent} onClick={()=>action(async()=>setXPost(await api<Publication>('x/videos/'+xPost.id,{consent:true})))}>Publish post ↗</button>}</div>{xPost.url&&<a href={xPost.url} target="_blank" rel="noreferrer">View post ↗</a>}</div>}</div>}
 </section>;
}
