'use client';
import {useEffect,useRef,useState,useCallback} from 'react';
import {useParams} from 'next/navigation';
type Campaign={id:string;title:string;description:string;source_asset_id:string;streamer_name:string;target_platforms:string[];license_terms:string;entry_fee_raw:string};
type Profile={name:string;wallet?:string;roles:string[];access:{status:string;balanceRaw?:string};config:{mint:string;network:string;decimals:number;clipperMinRaw:string}};
type Job={id:string;status:'queued'|'processing'|'succeeded'|'failed';output_asset_id?:string;error_message?:string};
type AiJob={id:string;status:'queued'|'processing'|'succeeded'|'failed';suggestions?:{start:number;end:number;score:number;hook:string;excerpt:string}[];transcript?:{start:number;end:number;text:string}[];error_message?:string};
type TikTokDraft={id:string;status:string;publish_id?:string;fail_reason?:string};
const csrf=()=>decodeURIComponent(document.cookie.split('; ').find(c=>c.startsWith('pc_csrf='))?.split('=')[1]||'');
async function request<T>(path:string,method='GET',body?:unknown):Promise<T>{
  const response=await fetch('/api/v1/'+path,{method,headers:method==='GET'?{}:{'content-type':'application/json','x-csrf-token':csrf(),'idempotency-key':crypto.randomUUID()},body:body?JSON.stringify(body):undefined});
  const data=await response.json();if(!response.ok) throw new Error(data.message||data.code||'Request failed');return data;
}
function stamp(seconds:number){if(!Number.isFinite(seconds))return '00:00';const m=Math.floor(seconds/60),s=Math.floor(seconds%60);return String(m).padStart(2,'0')+':'+String(s).padStart(2,'0');}
export default function StudioWorkspace(){
  const {id}=useParams<{id:string}>(),video=useRef<HTMLVideoElement>(null);
  const [campaign,setCampaign]=useState<Campaign|null>(null),[profile,setProfile]=useState<Profile|null>(null);
  const [loading,setLoading]=useState(true),[error,setError]=useState(''),[job,setJob]=useState<Job|null>(null),[busy,setBusy]=useState(false);
  const [duration,setDuration]=useState(0),[current,setCurrent]=useState(0),[start,setStart]=useState(0),[end,setEnd]=useState(30);
  const [caption,setCaption]=useState(''),[view,setView]=useState<'source'|'vertical'>('vertical'),[social,setSocial]=useState(''),[submitted,setSubmitted]=useState(false);
  const [playing,setPlaying]=useState(false);
  const [ai,setAi]=useState<AiJob|null>(null);
  const [youtubeTitle,setYoutubeTitle]=useState(''),[youtubeUrl,setYoutubeUrl]=useState(''),[youtubeUploadId,setYoutubeUploadId]=useState(''),[youtubeStatus,setYoutubeStatus]=useState('');
  const [tiktokDraft,setTiktokDraft]=useState<TikTokDraft|null>(null);
  useEffect(()=>{let active=true;(async()=>{try{
    const [c,me,joined]=await Promise.all([request<Campaign>('campaigns/'+id),request<Profile>('me'),request<Campaign[]>('me/joined')]);
    if(!joined.some(x=>x.id===id)) throw new Error('Join this campaign before opening its licensed footage.');
    if(active){setCampaign(c);setProfile(me);}
  }catch(e:any){if(active)setError(e.message);}finally{if(active)setLoading(false);}})();return()=>{active=false;};},[id]);
  useEffect(()=>{const saved=localStorage.getItem('pc_studio_job_'+id);if(!saved)return;request<Job>('studio/'+saved).then(setJob).catch(()=>localStorage.removeItem('pc_studio_job_'+id));},[id]);
  useEffect(()=>{if(!job||!['queued','processing'].includes(job.status))return;const timer=setInterval(async()=>{try{setJob(await request<Job>('studio/'+job.id));}catch(e:any){setError(e.message);}},2500);return()=>clearInterval(timer);},[job?.id,job?.status]);
  useEffect(()=>{if(!ai||!['queued','processing'].includes(ai.status))return;const timer=setInterval(async()=>{try{setAi(await request<AiJob>('ai/'+ai.id));}catch(e:any){setError(e.message);}},3000);return()=>clearInterval(timer);},[ai?.id,ai?.status]);
  async function analyze(){if(!campaign)return;setError('');try{setAi(await request<AiJob>('ai','POST',{campaignId:campaign.id}));}catch(e:any){setError(e.message);}}
  const seek=useCallback((time:number)=>{const next=Math.max(0,Math.min(duration||time,time));if(video.current)video.current.currentTime=next;setCurrent(next);},[duration]);
  const markIn=()=>setStart(Math.min(current,Math.max(0,end-.1)));
  const markOut=()=>setEnd(Math.max(current,start+.1));
  async function render(){setError('');if(!campaign)return;if(end<=start||end-start>180){setError('Select a segment between 0 and 180 seconds.');return;}
    setBusy(true);try{const created=await request<Job>('studio','POST',{campaignId:campaign.id,start:Number(start.toFixed(3)),end:Number(end.toFixed(3)),caption});setJob(created);localStorage.setItem('pc_studio_job_'+id,created.id);}
    catch(e:any){setError(e.message);}finally{setBusy(false);}
  }
  async function submit(){if(!job?.output_asset_id||!campaign)return;setBusy(true);setError('');
    try{await request('campaigns/'+campaign.id+'/submissions','POST',{assetId:job.output_asset_id,socialUrl:social||undefined});setSubmitted(true);}
    catch(e:any){setError(e.message);}finally{setBusy(false);}
  }
  async function publishYoutube(){if(!job?.output_asset_id)return;setBusy(true);setError('');try{const post=await request<{id:string;status:string;url?:string}>('social/youtube/publish','POST',{assetId:job.output_asset_id,title:youtubeTitle||campaign?.title||'Pumpclip highlight',description:'Edited with PUMPCLIP'});setYoutubeUploadId(post.id);setYoutubeStatus(post.status);if(post.url)setYoutubeUrl(post.url);}catch(e:any){setError(e.message);}finally{setBusy(false);}}
  async function checkYoutube(){if(!youtubeUploadId)return;setBusy(true);setError('');try{const upload=await request<{status:string;url?:string;message?:string}>('social/youtube/uploads/'+youtubeUploadId);setYoutubeStatus(upload.message||upload.status);if(upload.url)setYoutubeUrl(upload.url);}catch(e:any){setError(e.message);}finally{setBusy(false);}}
  async function uploadTikTok(){if(!job?.output_asset_id)return;setBusy(true);setError('');try{setTiktokDraft(await request<TikTokDraft>('social/tiktok/drafts','POST',{assetId:job.output_asset_id}));}catch(e:any){setError(e.message);}finally{setBusy(false);}}
  async function checkTikTok(){if(!tiktokDraft)return;setBusy(true);setError('');try{setTiktokDraft(await request<TikTokDraft>('social/tiktok/drafts/'+tiktokDraft.id));}catch(e:any){setError(e.message);}finally{setBusy(false);}}
  const source=campaign?.source_asset_id?'/api/v1/assets/'+campaign.source_asset_id:'';
  const percent=(n:number)=>duration?Math.max(0,Math.min(100,n/duration*100)):0;
  return <div className="studio-shell">
    <header className="studio-top"><a href="/" className="studio-logo" aria-label="Pumpclip home">P<span>/</span></a><div className="studio-title"><span>STUDIO / MANUAL EDIT</span><strong>{campaign?.title||'Clip workspace'}</strong></div><div className="studio-top-actions"><span className="studio-network"><i/>{profile?.config.network||'DEVNET'}</span><a className="studio-exit" href="/dashboard">Exit studio ↗</a></div></header>
    {loading?<main id="main-content" className="studio-loading" aria-busy="true"><div className="skeleton wide"/><div className="skeleton"/><p>Loading licensed footage…</p></main>:error&&!campaign?<main id="main-content" className="studio-error-page"><span>ACCESS / 403</span><h1>Studio unavailable</h1><p>{error}</p><a href="/dashboard">Back to campaigns ↗</a></main>:campaign&&<main id="main-content" className="studio-main">
      <div className="studio-heading"><div><p className="studio-kicker">CLIPPING WORKSPACE <span>·</span> {campaign.streamer_name}</p><h1>Find the moment.<br/><em>Make it travel.</em></h1></div><div className="studio-access"><span className={profile?.access.status==='eligible'?'ok':'not-ok'}>{profile?.access.status==='eligible'?'● HOLDER ACCESS VERIFIED':'● '+(profile?.access.status||'ACCESS UNAVAILABLE').toUpperCase()}</span><small>Mint {profile?.config.mint?profile.config.mint.slice(0,7)+'…'+profile.config.mint.slice(-6):'not configured'} · {profile?.config.network}</small></div></div>
      <div className="studio-grid"><section className="preview-panel" aria-label="Video preview"><div className="panel-toolbar"><div><span className="panel-index">01</span> PREVIEW</div><div className="view-switch" role="group" aria-label="Preview aspect ratio"><button className={view==='source'?'active':''} onClick={()=>setView('source')} aria-pressed={view==='source'}>Original</button><button className={view==='vertical'?'active':''} onClick={()=>setView('vertical')} aria-pressed={view==='vertical'}>9:16 crop</button></div></div>
        <div className={'video-stage '+(view==='vertical'?'is-vertical':'is-source')}><div className="video-frame"><video ref={video} src={source} controls playsInline preload="metadata" aria-label="Licensed campaign video" onLoadedMetadata={e=>{const d=e.currentTarget.duration;setDuration(d);setEnd(Math.min(d,30));}} onTimeUpdate={e=>{const now=e.currentTarget.currentTime;setCurrent(now);if(now>=end&&playing){e.currentTarget.pause();setPlaying(false);}}} onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} onError={()=>setError('The video could not load. Check your campaign membership and try again.')}/>{caption&&view==='vertical'&&<div className="caption-preview" aria-hidden="true">{caption}</div>}</div>{!duration&&<div className="video-placeholder" aria-hidden="true"><span>P/</span> LOAD YOUR SOURCE</div>}</div>
        <div className="transport"><button onClick={()=>seek(start)} aria-label="Go to clip start">↤ IN</button><span className="timecode">{stamp(current)} <small>/ {stamp(duration)}</small></span><button onClick={()=>seek(end)} aria-label="Go to clip end">OUT ↦</button></div>
      </section>
      <aside className="edit-panel"><div className="panel-toolbar"><div><span className="panel-index">02</span> EDIT CLIP</div><span className="manual-tag">MANUAL MODE</span></div><div className="edit-content"><div className="edit-intro"><h2>Your cut</h2><p>Choose the start and end of the moment. Keep it under three minutes for a short vertical export.</p></div><div className="edit-fields"><label>In point <span>{stamp(start)}</span><div className="input-action"><input type="number" min="0" max={duration||undefined} step=".1" value={start} onChange={e=>setStart(Number(e.target.value))}/><button type="button" onClick={markIn}>Use playhead</button></div></label><label>Out point <span>{stamp(end)}</span><div className="input-action"><input type="number" min="0" max={duration||undefined} step=".1" value={end} onChange={e=>setEnd(Number(e.target.value))}/><button type="button" onClick={markOut}>Use playhead</button></div></label></div><div className="duration-bar"><span>CLIP LENGTH</span><strong>{(end-start).toFixed(1)}s</strong><small>Maximum 180s</small></div><label className="caption-input">On-screen caption<textarea maxLength={200} rows={3} value={caption} onChange={e=>setCaption(e.target.value)} placeholder="Write a clear hook for this moment…"/><small>{caption.length}/200 · Burned into the exported video</small></label><div className="studio-note"><strong>About this editor</strong><p>Trim, vertical crop and captions run in a separate video worker. Use AI Assist below to transcribe source audio and suggest cuts when the AI worker is configured.</p></div></div></aside></div>
      <section className="timeline-panel" aria-label="Clip timeline"><div className="panel-toolbar"><div><span className="panel-index">03</span> TIMELINE</div><span className="timecode">{stamp(start)} — {stamp(end)}</span></div><div className="timeline-content"><label htmlFor="studio-scrub">Scrub source video</label><div className="timeline-track" style={{'--clip-start':percent(start)+'%','--clip-end':percent(end)+'%','--playhead':percent(current)+'%'} as React.CSSProperties}><div className="track-selected"/><div className="track-playhead"/><input id="studio-scrub" type="range" min="0" max={duration||1} step=".1" value={Math.min(current,duration||1)} onChange={e=>seek(Number(e.target.value))} aria-valuetext={stamp(current)}/></div><div className="timeline-labels"><span>00:00</span><span>{stamp(duration/2)}</span><span>{stamp(duration)}</span></div><div className="timeline-actions"><button onClick={markIn}>Set in at {stamp(current)}</button><button onClick={markOut}>Set out at {stamp(current)}</button><span>Highlighted region is your export</span></div></div></section>
      <section className="timeline-panel ai-panel" aria-label="Transcription and highlights"><div className="panel-toolbar"><div><span className="panel-index">04</span> TRANSCRIPT & HIGHLIGHTS</div><span className="manual-tag">AI ASSIST</span></div><div className="timeline-content"><p>Transcribe licensed footage and find candidate moments based on the spoken story. Review every suggestion before publishing. Available for sources up to 60 minutes when the AI worker is configured.</p><button className="render-button" onClick={analyze} disabled={!profile?.wallet||profile.access.status!=='eligible'||ai?.status==='queued'||ai?.status==='processing'}>{ai?.status==='queued'||ai?.status==='processing'?'Analyzing…':'Find highlights ↗'}</button>{ai?.error_message&&<p role="alert">{ai.error_message}</p>}{ai?.suggestions?.length? <div className="ai-suggestions">{ai.suggestions.map((s,i)=><button key={i} onClick={()=>{setStart(s.start);setEnd(s.end);seek(s.start);setCaption(s.hook.slice(0,200));}}><strong>{stamp(s.start)}–{stamp(s.end)}</strong><span>{s.excerpt}</span><small>Use this cut ↗</small></button>)}</div>:ai?.status==='succeeded'?<p>No suitable 15–90 second speech segments found. Continue editing manually.</p>:null}</div></section>
      <section className="export-panel" aria-label="Export and submit"><div><p className="studio-kicker">FINAL STEP / 05</p><h2>Ready to render?</h2><p>We’ll make a 1080 × 1920 MP4 with audio and the caption you wrote. Your original source stays intact.</p></div><div className="export-actions">{error&&<p role="alert" className="inline-error">{error}</p>}{job&&<div className="job-status" role="status"><span className={job.status==='succeeded'?'job-done':''}>{job.status==='queued'?'In the render queue':job.status==='processing'?'Rendering your clip':job.status==='succeeded'?'MP4 ready':'Render failed'}</span>{job.error_message&&<small>{job.error_message}</small>}</div>}<button className="render-button" onClick={render} disabled={busy||job?.status==='queued'||job?.status==='processing'||!profile?.wallet||profile.access.status!=='eligible'}>{busy?'Working…':job?.status==='failed'?'Retry render ↗':'Render clip ↗'}</button>{job?.output_asset_id&&<><a className="download-button" href={'/api/v1/assets/'+job.output_asset_id} download={'pumpclip-'+campaign.id.slice(0,8)+'.mp4'}>Download MP4 ↓</a><label className="publish-input">Published post URL (optional)<input type="url" value={social} onChange={e=>setSocial(e.target.value)} placeholder="https://www.tiktok.com/@…"/></label><button className="submit-button" onClick={submit} disabled={busy||submitted}>{submitted?'Submitted for review ✓':'Submit to campaign ↗'}</button><div className="youtube-publish"><strong>YouTube Shorts</strong><p>Connect your channel and upload this clip privately. Review it on YouTube before making it public.</p><a href="/api/v1/social/youtube">Connect YouTube channel ↗</a><label>Video title<input value={youtubeTitle} maxLength={100} onChange={e=>setYoutubeTitle(e.target.value)} placeholder={campaign.title}/></label><button className="submit-button" onClick={publishYoutube} disabled={busy||!!youtubeUrl}>Upload private Short ↗</button>{youtubeUploadId&&<><p role="status">Upload: {youtubeStatus}</p><button className="download-button" onClick={checkYoutube} disabled={busy}>Check upload status ↻</button></>}{youtubeUrl&&<a href={youtubeUrl} target="_blank" rel="noreferrer">View private upload ↗</a>}</div><div className="youtube-publish"><strong>TikTok draft</strong><p>Connect TikTok, send this clip to your inbox, then open TikTok to edit and publish it. Uploading does not publish a post.</p><a href="/api/v1/social/tiktok">Connect TikTok ↗</a><button className="submit-button" onClick={uploadTikTok} disabled={busy||!!tiktokDraft}>{busy?'Uploading…':'Send draft to TikTok ↗'}</button>{tiktokDraft&&<><p role="status">Draft status: {tiktokDraft.status}{tiktokDraft.fail_reason?' · '+tiktokDraft.fail_reason:''}</p><button className="download-button" onClick={checkTikTok} disabled={busy}>Check TikTok status ↻</button></>}</div></>}</div></section>
      <div className="studio-footnote">SOURCE RIGHTS: {campaign.license_terms||'Review campaign rules before publishing.'} <a href="/dashboard">Return to campaign ↗</a></div>
    </main>}</div>;
}
