'use client';
import {FormEvent,useEffect,useState} from 'react';
type Ingestion={id:string;channel_url:string;status:string;max_videos:number;discovered_count:number;queued_count:number;video_count:number;completed_video_count:number;failed_video_count:number;error_message?:string|null};
function csrf(){return document.cookie.split('; ').find(value=>value.startsWith('pc_csrf='))?.slice(8)||'';}
export default function ChannelIngestion(){
  const [url,setUrl]=useState(''); const [maxVideos,setMaxVideos]=useState('100'); const [busy,setBusy]=useState(false); const [notice,setNotice]=useState(''); const [latest,setLatest]=useState<Ingestion|null>(null);
  const refresh=async()=>{const response=await fetch('/api/v1/ingestion/youtube',{headers:{'x-csrf-token':csrf()},credentials:'include'});if(response.ok){const rows=await response.json();setLatest(rows[0]||null);}};
  useEffect(()=>{refresh();},[]);
  useEffect(()=>{if(!latest||!['queued','processing'].includes(latest.status))return;const timer=window.setInterval(refresh,5000);return()=>window.clearInterval(timer);},[latest?.id,latest?.status]);
  async function submit(event:FormEvent){event.preventDefault();setBusy(true);setNotice('');try{const response=await fetch('/api/v1/ingestion/youtube',{method:'POST',headers:{'content-type':'application/json','x-csrf-token':csrf()},credentials:'include',body:JSON.stringify({channelUrl:url,maxVideos:Number(maxVideos)})});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||data.code||'Channel ingestion failed');setLatest(data);setUrl('');setNotice('Channel accepted. We are enumerating the videos and queueing one clip per video.');}catch(error){setNotice(error instanceof Error?error.message:'Channel ingestion failed');}finally{setBusy(false);}}
  const progress=latest?.video_count?`${latest.completed_video_count||0}/${latest.video_count} clips complete`:latest?.status==='processing'?'Discovering videos…':'No channel run yet';
  return <section className="panel channel-ingestion"><div className="panel-heading"><div><p className="kicker">AUTOMATION / YOUTUBE CHANNEL</p><h2>Clip every upload.</h2></div><span className="channel-status">{latest?.status||'READY'}</span></div><p className="channel-copy">Paste a channel URL and pumpclips will discover its video library, queue one native vertical clip per video, and keep the results tied to this run.</p><form className="channel-form" onSubmit={submit}><input type="url" required value={url} onChange={event=>setUrl(event.target.value)} placeholder="https://youtube.com/@creator" aria-label="YouTube channel URL"/><select value={maxVideos} onChange={event=>setMaxVideos(event.target.value)} aria-label="Maximum videos"><option value="25">25 videos</option><option value="100">100 videos</option><option value="250">250 videos</option><option value="500">500 videos</option></select><button className="primary-action" disabled={busy}>{busy?'Queueing…':'Start ingestion ↗'}</button></form>{latest&&<div className="channel-progress"><div><strong>{progress}</strong><span>{latest.queued_count||0} clip jobs queued · {latest.discovered_count||0} videos discovered</span></div><div className="channel-meter"><i style={{width:`${latest.video_count?Math.min(100,((latest.completed_video_count||0)+(latest.failed_video_count||0))/latest.video_count*100):0}%`}}/></div></div>}{notice&&<p className="channel-notice" role="status">{notice}</p>}{latest?.error_message&&<p className="channel-error" role="alert">{latest.error_message}</p>}<small className="channel-note">Each queued clip uses 5 AI units. Videos are processed in the background; the page can be closed safely.</small></section>;
}
