import pg from 'pg';
const databaseUrl=process.env.DATABASE_URL||'';
const ssl=process.env.DATABASE_SSL==='disable'?undefined:(databaseUrl?{rejectUnauthorized:false}:undefined);
import fs from 'node:fs';
import {Connection,PublicKey} from '@solana/web3.js';
import {S3Client,HeadBucketCommand} from '@aws-sdk/client-s3';
import {spawnSync} from 'node:child_process';
const results=[];
async function check(name,fn){try{await fn();results.push({name,status:'ok'});}catch(e){results.push({name,status:'blocked',reason:String(e.message||e)});}}
const full=process.env.READINESS_MODE==='full';
await check('HTTPS origin',()=>{if(!process.env.APP_URL?.startsWith('https://'))throw new Error('APP_URL must be HTTPS');});
await check('Staging domain and database TLS',()=>{if(!process.env.STAGING_DOMAIN)return;const origin=new URL(process.env.APP_URL||'');if(origin.protocol!=='https:'||origin.hostname!==process.env.STAGING_DOMAIN)throw new Error('APP_URL must match https://STAGING_DOMAIN');const db=new URL(process.env.DATABASE_URL||'');if(process.env.DATABASE_SSL==='disable')throw new Error('Managed PostgreSQL requires TLS; do not set DATABASE_SSL=disable');});
await check('Google OAuth',()=>{if(!process.env.GOOGLE_CLIENT_ID||!process.env.GOOGLE_CLIENT_SECRET)throw new Error('Client credentials missing');});
await check('Devnet RPC',async()=>{if(process.env.SOLANA_CLUSTER!=='devnet')throw new Error('Only devnet is supported');const c=new Connection(process.env.SOLANA_RPC_URL||'https://api.devnet.solana.com');if(await c.getGenesisHash()!=='GH7ome3EiwEr7tu9JuTh2dpYWBJK3z69Xm1ZE3MEE6JC')throw new Error('Wrong cluster');});
await check('Mint and treasuries',()=>{for(const name of ['PUMPCLIP_MINT','TOKEN_TREASURY','SOL_TREASURY'])new PublicKey(process.env[name]);});
await check('PostgreSQL migrations',async()=>{const db=new pg.Client({connectionString:databaseUrl,ssl});await db.connect();try{const applied=new Set((await db.query('SELECT name FROM schema_migrations')).rows.map(row=>row.name));const current=fs.readdirSync('db/migrations').filter(name=>/^\d+_.+\.sql$/.test(name)).sort();for(const name of current)if(!applied.has(name))throw new Error('Missing '+name);}finally{await db.end();}});
await check('Private media bucket',async()=>{if(!process.env.MEDIA_BUCKET)throw new Error('MEDIA_BUCKET missing; staging requires private object storage');const hasKey=Boolean(process.env.MEDIA_ACCESS_KEY_ID),hasSecret=Boolean(process.env.MEDIA_SECRET_ACCESS_KEY);if(hasKey!==hasSecret)throw new Error('MEDIA_ACCESS_KEY_ID and MEDIA_SECRET_ACCESS_KEY must be provided together');const client=new S3Client({region:process.env.MEDIA_REGION||'auto',endpoint:process.env.MEDIA_ENDPOINT||undefined,forcePathStyle:!!process.env.MEDIA_ENDPOINT,credentials:hasKey?{accessKeyId:process.env.MEDIA_ACCESS_KEY_ID,secretAccessKey:process.env.MEDIA_SECRET_ACCESS_KEY}:undefined});await client.send(new HeadBucketCommand({Bucket:process.env.MEDIA_BUCKET}));});
await check('FFmpeg',()=>{if(spawnSync('ffmpeg',['-version']).status!==0||spawnSync('ffprobe',['-version']).status!==0)throw new Error('FFmpeg and ffprobe required');});
const optional=[['AI provider',()=>{if(!process.env.OPENAI_API_KEY)throw new Error('OPENAI_API_KEY missing');}],['YouTube encryption',()=>{if(Buffer.from(process.env.SOCIAL_TOKEN_KEY||'','base64').length!==32)throw new Error('SOCIAL_TOKEN_KEY must be 32 bytes');}],['TikTok app',()=>{if(!process.env.TIKTOK_CLIENT_KEY||!process.env.TIKTOK_CLIENT_SECRET)throw new Error('TikTok credentials missing');}],['Instagram app',()=>{if(!process.env.META_APP_ID||!process.env.META_APP_SECRET)throw new Error('Meta credentials missing');}],['X app',()=>{if(!process.env.X_CLIENT_ID||!process.env.X_CLIENT_SECRET)throw new Error('X credentials missing');}]];
for(const [name,fn] of optional)await check(full?name:`Optional ${name}`,fn);
console.log(JSON.stringify({mode:full?'full':'core',results},null,2));if(results.some(r=>r.status==='blocked'&&(!r.name.startsWith('Optional ')||full)))process.exitCode=1;
