'use client';
import {useEffect,useMemo,useState} from 'react';

type Person={id:string;display_name:string;roles:string[];accepted_count:number;total_views:number;reputation_score:number;campaign_title?:string;video_url?:string};

export default function PeoplePage(){
  const [people,setPeople]=useState<Person[]>([]),[role,setRole]=useState<'all'|'streamer'|'clipper'>('all'),[error,setError]=useState(''),[loading,setLoading]=useState(true);
  useEffect(()=>{fetch('/api/v1/profiles?limit=60').then(r=>r.ok?r.json():Promise.reject()).then(x=>setPeople(x.items||[])).catch(()=>setError('The people directory is temporarily unavailable.')).finally(()=>setLoading(false));},[]);
  const visible=useMemo(()=>role==='all'?people:people.filter(person=>person.roles.includes(role)),[people,role]);
  return <main className="people-page"><header className="people-header"><a className="brand official-brand" href="/"><img src="/pumpclips-mark.jpg" alt="" /> <span>pumpclips</span></a><div><span className="eyebrow">NETWORK / PUBLIC DIRECTORY</span><a className="outline" href="/feed">Watch live cuts ↗</a></div></header><section className="people-intro"><div><span className="eyebrow">CREATORS + CLIPPERS / {people.length||'—'}</span><h1>The people<br/><em>behind the momentum.</em></h1><p>Meet the creators who publish the source and the clippers who turn it into work worth watching.</p></div><div className="people-filter" role="tablist" aria-label="Filter people">{[['all','Everyone'],['streamer','Creators'],['clipper','Clippers']].map(([key,label])=><button key={key} className={role===key?'active':''} onClick={()=>setRole(key as typeof role)}>{label}</button>)}</div></section>{loading?<div className="people-state">Loading the network…</div>:error?<div className="people-state error">{error}</div>:visible.length===0?<div className="people-state">No public profiles yet. Publish the first accepted clip to start the network.</div>:<section className="people-grid">{visible.map(person=><a className="directory-card" href={'/profile/'+person.id} key={person.id}><div className="directory-card-top"><span className="directory-avatar">{person.display_name.slice(0,2).toUpperCase()}</span><span className="directory-role">{person.roles.map(item=>item==='streamer'?'CREATOR':'CLIPPER').join(' · ')}</span><b>↗</b></div><h2>{person.display_name}</h2><div className="directory-stats"><span><strong>{Number(person.reputation_score||0).toFixed(1)}</strong><small>reputation</small></span><span><strong>{Number(person.accepted_count||0)}</strong><small>accepted cuts</small></span><span><strong>{Number(person.total_views||0).toLocaleString()}</strong><small>views</small></span></div>{person.video_url?<div className="directory-video"><video src={person.video_url} muted loop autoPlay playsInline preload="metadata"/><span>{person.campaign_title||'Accepted work'}</span></div>:<div className="directory-empty">Profile ready for first accepted work.</div>}</a>)}</section>}<footer><strong className="footer-brand"><img src="/pumpclips-mark.jpg" alt="" /> pumpclips</strong><span>Turn moments into momentum.</span><a href="/dashboard">Open workspace ↗</a></footer></main>;
}
