'use client';

import {FormEvent, useEffect, useMemo, useState} from 'react';
import './dashboard.css';
import ClipEngine from './clip-engine';
import PumpFunLive from '@/app/pumpfun-live';

type User={user_id:string;display_name:string;roles:string[];public_handle?:string|null};
type Campaign={id:string;title:string;description:string;category:string;state:string;streamer_id:string;created_at:string;source_url?:string|null;fixed_reward_lamports?:string|number;target_platforms?:string[]};
type Submission={id:string;campaign_id:string;clipper_name:string;state:string;review_reason?:string|null;created_at:string};
type Profile={id:string;display_name:string;public_handle?:string|null;roles:string[];reputation_score:number;accepted_count:number;total_views:number};
type Message={id:string;sender_id:string;sender_name:string;body:string;created_at:string};
type ApiError=Error & {code?:string};

const sections=['overview','clip-engine','discover','brief','review','portfolio','messages'] as const;
type Section=typeof sections[number];
const csrf=()=>decodeURIComponent(document.cookie.split('; ').find(c=>c.startsWith('pc_csrf='))?.split('=')[1]||'');
async function api<T>(url:string,init?:RequestInit):Promise<T>{const response=await fetch(url,{...init,cache:'no-store',headers:{...(init?.body?{'content-type':'application/json'}:{}),...(init?.headers||{})}});const data=await response.json().catch(()=>({}));if(!response.ok){const error=new Error(data.message||data.code||'Request failed') as ApiError;error.code=data.code;throw error;}return data as T;}

function Nav({section,setSection}:{section:Section;setSection:(value:Section)=>void}){return <nav className="command-nav" aria-label="Workspace sections">{[['overview','⌂','Overview'],['clip-engine','✂','Clip engine'],['discover','◈','Discover'],['brief','▣','Create brief'],['review','✓','Review'],['portfolio','♧','People'],['messages','✉','Messages']].map(([key,icon,label])=><button type="button" key={key} className={section===key?'selected':''} onClick={()=>setSection(key as Section)}><span className="icon" aria-hidden="true">{icon}</span><span>{label}</span></button>)}</nav>}

export default function Dashboard(){
 const [section,setSection]=useState<Section>('overview');
 const [user,setUser]=useState<User|null>(null),[authError,setAuthError]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const [owned,setOwned]=useState<Campaign[]>([]),[joined,setJoined]=useState<Campaign[]>([]),[discover,setDiscover]=useState<Campaign[]>([]),[profiles,setProfiles]=useState<Profile[]>([]);
 const [selectedCampaign,setSelectedCampaign]=useState<Campaign|null>(null),[submissions,setSubmissions]=useState<Submission[]>([]),[messages,setMessages]=useState<Message[]>([]),[messageText,setMessageText]=useState(''),[disputeText,setDisputeText]=useState('');
 const [brief,setBrief]=useState({title:'',description:'',category:'General',sourceUrl:'',targetPlatforms:'tiktok,youtube',reward:'',licenseTerms:''});
 const [busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const visibleCampaigns=useMemo(()=>discover.filter(c=>c.state==='live'),[discover]);
 const showError=(e:unknown)=>setError(e instanceof Error?e.message:'Request failed');
 const refresh=async()=>{setLoading(true);setError('');try{const me=await api<User>('/api/v1/me');setUser(me);const [mine,joinedData,publicCampaigns,people]=await Promise.all([api<Campaign[]>('/api/v1/me/campaigns'),api<Campaign[]>('/api/v1/me/joined'),api<{items:Campaign[]}>('/api/v1/campaigns').catch(()=>({items:[]})),api<{items:Profile[]}>('/api/v1/profiles?limit=60')]);setOwned(mine);setJoined(joinedData);setDiscover(publicCampaigns.items||[]);setProfiles(people.items||[]);}catch(e){if((e as ApiError)?.code==='SIGN_IN_REQUIRED'){setAuthError('Sign in to use your workspace.');}else showError(e);}finally{setLoading(false);}};
 useEffect(()=>{void refresh();const view=new URLSearchParams(location.search).get('view') as Section|null;if(view&&sections.includes(view))setSection(view);},[]);
 const openSection=(value:Section)=>{setSection(value);const params=new URLSearchParams(location.search);if(value==='overview')params.delete('view');else params.set('view',value);history.replaceState(null,'',`${location.pathname}${params.toString()?`?${params}`:''}`);};
 const loadCampaignData=async(campaign:Campaign)=>{setSelectedCampaign(campaign);setError('');try{const [sub,messageData]=await Promise.all([api<Submission[]>(`/api/v1/campaigns/${campaign.id}/submissions`),api<{items:Message[]}>(`/api/v1/campaigns/${campaign.id}/messages`)]);setSubmissions(sub);setMessages(messageData.items||[]);}catch(e){showError(e);}};
 const createBrief=async(event:FormEvent)=>{event.preventDefault();setBusy(true);setError('');try{const created=await api<Campaign>('/api/v1/campaigns',{method:'POST',headers:{'x-csrf-token':csrf(),'idempotency-key':crypto.randomUUID()},body:JSON.stringify({title:brief.title,description:brief.description,category:brief.category,sourceUrl:brief.sourceUrl||undefined})});const updated=await api<Campaign>(`/api/v1/campaigns/${created.id}`,{method:'PATCH',headers:{'x-csrf-token':csrf()},body:JSON.stringify({licenseTerms:brief.licenseTerms||'Licensed source declared by creator.',targetPlatforms:brief.targetPlatforms.split(',').map(x=>x.trim()).filter(Boolean),fixedRewardLamports:brief.reward||'0'})});setOwned(old=>[updated,...old]);setNotice('Draft created in your account. Complete funding before publishing.');setBrief({title:'',description:'',category:'General',sourceUrl:'',targetPlatforms:'tiktok,youtube',reward:'',licenseTerms:''});openSection('overview');}catch(e){showError(e);}finally{setBusy(false);}};
 const review=async(submissionId:string,decision:'approved'|'rejected')=>{if(!selectedCampaign)return;setBusy(true);try{await api(`/api/v1/submissions/${submissionId}/review`,{method:'POST',headers:{'x-csrf-token':csrf()},body:JSON.stringify({decision,reason:decision==='approved'?'Approved after creator review.':'Revision requested by creator.'})});await loadCampaignData(selectedCampaign);setNotice(`Submission ${decision}.`);}catch(e){showError(e);}finally{setBusy(false);}};
 const sendMessage=async(event:FormEvent)=>{event.preventDefault();if(!selectedCampaign||!messageText.trim())return;setBusy(true);try{await api(`/api/v1/campaigns/${selectedCampaign.id}/messages`,{method:'POST',headers:{'x-csrf-token':csrf()},body:JSON.stringify({body:messageText.trim()})});setMessageText('');await loadCampaignData(selectedCampaign);}catch(e){showError(e);}finally{setBusy(false);}};
 const openDispute=async()=>{if(!selectedCampaign||disputeText.trim().length<10){setError('Add at least 10 characters describing the issue.');return;}setBusy(true);try{await api(`/api/v1/campaigns/${selectedCampaign.id}/disputes`,{method:'POST',headers:{'x-csrf-token':csrf()},body:JSON.stringify({reason:'other',description:disputeText.trim()})});setDisputeText('');setNotice('Dispute opened and recorded for customer care.');}catch(e){showError(e);}finally{setBusy(false);}};
 if(loading)return <main className="command-shell"><section className="page-section"><p role="status">Loading your workspace…</p></section></main>;
 if(authError)return <main className="command-shell"><section className="page-section"><div className="clip-engine-signin"><strong>{authError}</strong><span>Your campaigns, messages, reviews, and clip jobs are private.</span><a href="/auth">Sign in or create an account ↗</a></div></section></main>;
 const cards=[['LIVE CAMPAIGNS',discover.length],['YOUR DRAFTS',owned.filter(c=>c.state==='draft').length],['IN REVIEW',submissions.filter(s=>['submitted','in_review'].includes(s.state)).length],['JOINED CAMPAIGNS',joined.length]];
 return <div className="command-shell"><aside className="command-sidebar"><a className="command-brand official-command-brand" href="/"><img src="/logo.svg" alt=""/><strong>pumpclips</strong><small>WORKSPACE</small></a><div className="workspace-switcher"><span className="workspace-avatar">{user?.display_name?.slice(0,2).toUpperCase()}</span><div><strong>{user?.display_name}</strong><small>{user?.roles?.join(' · ')||'Account'}</small></div></div><div className="workspace-profile-links"><a href={user?.public_handle?`/profile/${user.user_id}`:'/settings'}>{user?.public_handle?'View my public profile ↗':'Set up my public profile ↗'}</a><a href="/settings">Edit profile details</a></div><Nav section={section} setSection={openSection}/><div className="sidebar-bottom"><div className="help-card"><strong>Need support?</strong><span>Open a campaign-linked case.</span><button type="button" onClick={()=>openSection('messages')}>Open messages ↗</button></div></div></aside><main className="command-main"><header className="command-topbar"><div className="crumb">pumpclips <span>/</span> {section.toUpperCase()}</div><div className="top-actions"><button className="icon-button" type="button" onClick={()=>void refresh()} aria-label="Refresh workspace">↻</button><div className="mini-avatar">{user?.display_name?.slice(0,2).toUpperCase()}</div></div></header>{error&&<p className="clip-engine-error" role="alert">{error}</p>}{notice&&<p className="clip-engine-notice" role="status">{notice}</p>}
 {section==='clip-engine'&&<ClipEngine/>}
 {section==='overview'&&<section className="page-section"><div className="welcome-row"><div><p className="kicker">ACCOUNT WORKSPACE</p><h1>Welcome back, {user?.display_name?.split(' ')[0]}<span>.</span></h1><p className="subhead">Live campaigns, private renders, reviews, and messages from your account.</p></div><button className="primary-action" onClick={()=>openSection('brief')}>＋ Create campaign</button></div><section className="metric-grid" aria-label="Live workspace metrics">{cards.map(([label,value])=><div className="metric-card" key={label as string}><span className="metric-label">{label as string}</span><strong className="metric-value">{value as number}</strong><small className="metric-trend">From your account</small></div>)}</section><PumpFunLive/><div className="dashboard-grid"><section className="panel campaign-panel"><div className="panel-heading"><div><p className="kicker">DISCOVER</p><h2>Live campaigns</h2></div><button className="text-button" onClick={()=>openSection('discover')}>View all ↗</button></div>{visibleCampaigns.slice(0,5).map(c=><button className="brief-row" key={c.id} onClick={()=>void loadCampaignData(c)}><div className="brief-info"><span className="pill">{c.category}</span><h3>{c.title}</h3><p>{c.description?.slice(0,100)||'No description yet.'}</p></div><span className="row-arrow">↗</span></button>)}{visibleCampaigns.length===0&&<p className="clip-engine-empty">No live campaigns yet. Create and fund the first one.</p>}</section><section className="panel review-panel"><div className="panel-heading"><div><p className="kicker">YOUR CAMPAIGNS</p><h2>Drafts and live work</h2></div><button className="text-button" onClick={()=>openSection('brief')}>New brief ↗</button></div>{owned.slice(0,5).map(c=><button className="review-summary" key={c.id} onClick={()=>void loadCampaignData(c)}><div><strong>{c.title}</strong><span>{c.state.toUpperCase()} · {new Date(c.created_at).toLocaleDateString()}</span></div><span className="status-dot"/></button>)}{owned.length===0&&<p className="clip-engine-empty">Your saved campaigns will appear here.</p>}</section></div></section>}
 {section==='discover'&&<section className="page-section"><div className="page-heading"><div><p className="kicker">MARKETPLACE / {discover.length} LIVE</p><h1>Find work that fits.</h1><p>Every card below is loaded from the campaign marketplace.</p></div></div><div className="discover-grid">{discover.map(c=><article className="discover-card" key={c.id} onClick={()=>void loadCampaignData(c)}><div className="discover-cover"><span>{c.category}</span></div><div className="discover-body"><h3>{c.title}</h3><p>{c.description||'Creator brief'}</p><div className="discover-footer"><small>{c.state}</small><span className="row-arrow">↗</span></div></div></article>)}</div>{discover.length===0&&<p className="clip-engine-empty">No funded campaigns are live yet.</p>}</section>}
 {section==='brief'&&<section className="page-section"><div className="page-heading"><div><p className="kicker">CREATOR WORKFLOW / SAVED TO DATABASE</p><h1>Create a real campaign brief.</h1><p>This form creates a draft, then persists its creative and reward requirements.</p></div></div><form className="builder-form panel" onSubmit={createBrief}><label>Campaign name<input required minLength={5} value={brief.title} onChange={e=>setBrief({...brief,title:e.target.value})}/></label><label>Description<textarea required value={brief.description} onChange={e=>setBrief({...brief,description:e.target.value})}/></label><div className="form-two"><label>Category<select value={brief.category} onChange={e=>setBrief({...brief,category:e.target.value})}><option>General</option><option>Business</option><option>Tech</option><option>Culture</option><option>Wellness</option><option>Pump.fun Content</option></select></label><label>Reward per clip (token base units)<input inputMode="numeric" value={brief.reward} onChange={e=>setBrief({...brief,reward:e.target.value.replace(/\D/g,'')})} placeholder="Configure before funding"/></label></div><label>Source URL (optional)<input type="url" value={brief.sourceUrl} onChange={e=>setBrief({...brief,sourceUrl:e.target.value})} placeholder="https://…"/></label><label>Target platforms<input value={brief.targetPlatforms} onChange={e=>setBrief({...brief,targetPlatforms:e.target.value})} placeholder="tiktok,youtube"/></label><label>Rights / license terms<textarea required minLength={10} value={brief.licenseTerms} onChange={e=>setBrief({...brief,licenseTerms:e.target.value})}/></label><button className="primary-action" disabled={busy}>{busy?'Saving…':'Save campaign draft ↗'}</button><p className="clip-engine-disclaimer">Publishing still requires the configured token fee, SOL escrow, licensed source asset, and wallet verification.</p></form></section>}
 {section==='review'&&<section className="page-section"><div className="page-heading"><div><p className="kicker">SUBMISSION REVIEW / LIVE DATA</p><h1>Review your submissions.</h1><p>Select one of your campaigns to load its actual submissions.</p></div></div><div className="review-layout"><div className="submission-list">{owned.map(c=><button className={'submission-item '+(selectedCampaign?.id===c.id?'selected':'')} key={c.id} onClick={()=>void loadCampaignData(c)}><span><strong>{c.title}</strong><small>{c.state}</small></span></button>)}</div><div className="review-workspace panel">{selectedCampaign?<><h2>{selectedCampaign.title}</h2>{submissions.map(s=><article className="review-summary" key={s.id}><div><strong>{s.clipper_name}</strong><span>{s.state} · {new Date(s.created_at).toLocaleString()}</span></div>{['submitted','in_review'].includes(s.state)&&<div><button className="approve-button" disabled={busy} onClick={()=>void review(s.id,'approved')}>Approve</button><button className="revision-button" disabled={busy} onClick={()=>void review(s.id,'rejected')}>Request revision</button></div>}</article>)}{submissions.length===0&&<p className="clip-engine-empty">No submissions for this campaign yet.</p>}</>:<p className="clip-engine-empty">Select a campaign to load its review queue.</p>}</div></div></section>}
 {section==='portfolio'&&<section className="page-section"><div className="page-heading"><div><p className="kicker">NETWORK / LIVE PROFILES</p><h1>People with verified work.</h1><p>Profiles and reputation are loaded from the public directory.</p></div></div><div className="portfolio-grid">{profiles.map(p=><article className="portfolio-card" key={p.id}><div className="portfolio-content"><h3>{p.display_name}</h3><p>{p.public_handle?`@${p.public_handle}`:p.roles.join(' · ')}</p><div className="portfolio-stats"><div><strong>{Number(p.reputation_score||0).toFixed(1)}</strong><small>Reputation</small></div><div><strong>{p.accepted_count}</strong><small>Accepted cuts</small></div><div><strong>{Number(p.total_views||0).toLocaleString()}</strong><small>Views</small></div></div><a className="message-button" href={`/profile/${p.id}`}>View profile ↗</a></div></article>)}</div></section>}
 {section==='messages'&&<section className="page-section"><div className="page-heading"><div><p className="kicker">CAMPAIGN CHAT / PERSISTED</p><h1>Keep the work in one place.</h1><p>Messages and disputes are stored against a campaign and visible to its participants.</p></div></div><div className="chat-layout"><aside className="chat-list">{[...owned,...joined].map(c=><button className={'chat-item '+(selectedCampaign?.id===c.id?'active':'')} key={c.id} onClick={()=>void loadCampaignData(c)}><span><strong>{c.title}</strong><small>{c.state}</small></span></button>)}</aside><div className="chat-window panel">{selectedCampaign?<><div className="chat-header"><div><strong>{selectedCampaign.title}</strong><span>Campaign conversation</span></div></div><div className="chat-messages">{messages.map(m=><div className={'chat-bubble '+(m.sender_id===user?.user_id?'sent':'received')} key={m.id}>{m.body}<small>{m.sender_name} · {new Date(m.created_at).toLocaleString()}</small></div>)}{messages.length===0&&<p className="clip-engine-empty">No messages yet.</p>}</div><form className="chat-composer" onSubmit={sendMessage}><input value={messageText} onChange={e=>setMessageText(e.target.value)} placeholder="Write a campaign message…"/><button disabled={busy||!messageText.trim()}>Send ↗</button></form><div className="dispute-inline"><textarea value={disputeText} onChange={e=>setDisputeText(e.target.value)} placeholder="Describe a payment, rights, or revision issue (10+ characters)…"/><button className="outline-action" onClick={()=>void openDispute()} disabled={busy}>Open dispute</button></div></>:<p className="clip-engine-empty">Select a campaign to load its persisted conversation.</p>}</div></div></section>}
 </main></div>;
}
